### ISSUE TITLE
icons are missing

### ISSUE THREAD

**Issue by Klumbumbus** [yopaseopor/traffic_signs_preset_JOSM#1]
Nearly all the icons are missing in the zip file. (Maybe also the icon paths in the xml file needs to be updated.)
This creates an endless list of errors in the JOSM jenkins test: https://josm.openstreetmap.de/jenkins/job/JOSM/1226/jdk=JDK7/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/testValidityOfAvailablePresets/

**Comment by yopaseopor** [comment]
done?
