### ISSUE TITLE
Icon link wrong

### ISSUE THREAD

**Issue by stoecker** [yopaseopor/traffic_signs_preset_JOSM#14]
Hello,

as already sent by mail: please fix the icon link of the traffic signs presets. The error messages are
spamming my mailbox. You moved everything a level up in the zip file I assume.

If the issue is not fixed I'll disable the presets in wiki.

Error with Image for A.zip - A_.png: caution: filename not matched:  A_.png
Error with Image for AD.zip - AD_.png: caution: filename not matched:  AD_.png
Error with Image for AR.zip - AR_.png: caution: filename not matched:  AR_.png
Error with Image for AU.zip - AU_.png: caution: filename not matched:  AU_.png
Error with Image for BE.zip - BE_.png: caution: filename not matched:  BE_.png
Error with Image for BR.zip - BR_.png: caution: filename not matched:  BR_.png
Error with Image for BY.zip - BY_.png: caution: filename not matched:  BY_.png
Error with Image for CH.zip - CH_.png: caution: filename not matched:  CH_.png
Error with Image for CL.zip - CL_.png: caution: filename not matched:  CL_.png
Error with Image for CO.zip - CO_.png: caution: filename not matched:  CO_.png
Error with Image for CZ.zip - CZ_.png: caution: filename not matched:  CZ_.png
Error with Image for DE.zip - DE_.png: caution: filename not matched:  DE_.png
Error with Image for DK.zip - DK_.png: caution: filename not matched:  DK_.png
Error with Image for EE.zip - EE_.png: caution: filename not matched:  EE_.png
Error with Image for ES.zip - ES_.png: caution: filename not matched:  ES_.png
Error with Image for FI.zip - FI_.png: caution: filename not matched:  FI_.png
Error with Image for FR.zip - FR_.png: caution: filename not matched:  FR_.png
Error with Image for GB.zip - GB_.png: caution: filename not matched:  GB_.png
Error with Image for GR.zip - GR_.png: caution: filename not matched:  GR_.png
Error with Image for HU.zip - HU_.png: caution: filename not matched:  HU_.png
Error with Image for ID.zip - ID_.png: caution: filename not matched:  ID_.png
Error with Image for IR.zip - IR_.png: caution: filename not matched:  IR_.png
Error with Image for IS.zip - IS_.png: caution: filename not matched:  IS_.png
Error with Image for IT.zip - IT_.png: caution: filename not matched:  IT_.png
Error with Image for NL.zip - NL_.png: caution: filename not matched:  NL_.png
Error with Image for NO.zip - NO_.png: caution: filename not matched:  NO_.png
Error with Image for PE.zip - PE_.png: caution: filename not matched:  PE_.png
Error with Image for PL.zip - PL_.png: caution: filename not matched:  PL_.png
Error with Image for RU.zip - RU_.png: caution: filename not matched:  RU_.png
Error with Image for SE.zip - SE_.png: caution: filename not matched:  SE_.png
Error with Image for SK.zip - SK_.png: caution: filename not matched:  SK_.png
Error with Image for TR.zip - TR_.png: caution: filename not matched:  TR_.png
Error with Image for UA.zip - UA_.png: caution: filename not matched:  UA_.png
Error with Image for US.zip - US_.png: caution: filename not matched:  US_.png

**Comment by yopaseopor** [comment]
Hi!, I have checked the preset inside, and I know it is something
wrong...but I don't see the error itself. So I ask: Is this error inside
the preset or are you refering to the icon of the preset in the
wiki...because I see it correctly. Please , help me.
Thanks

**Comment by stoecker** [comment]
Right, seems a bit more complicated. I'm checking where exactly that message comes from. BTW: external links aren't recommended (causing addition network traffic) . Better is to include the file in the zip and reference it.

**Comment by stoecker** [comment]
Ok. Seems it was a bug related to the icon links. Icon links in zip files haven't been supported. As said I'd recommend to include the file instead, but the issue is solved on JOSM side.

**Comment by yopaseopor** [comment]
Ok, I will try it with the next presets for China, Japan and South Korea. I
hope it will work. If there will be some mistake in these new future
presets please warn me.

Thanks
I try to do it the best I could
yopaseopor
