### ISSUE TITLE
Typo in BE.zip

### ISSUE THREAD

**Issue by timcouwelier** [yopaseopor/traffic_signs_preset_JOSM#23]
As local belgian mapper 'Jakka' pointed out - there's a value maxwheight preset, which has an extra 'w' where it shouldn't be and giving invalid keys.

Ideally this gets updated to remove the extra letter 'w'.

**Comment by yopaseopor** [comment]
Fixed. Thanks for your warning, and for using the preset

**Comment by Jakkajakka** [comment]
When reinstalling get a error ... and saw type error but in wich application ?
![error](https://user-images.githubusercontent.com/11509181/80807082-82a22b80-8bbc-11ea-9622-e8598fea7f67.jpg)
