### ISSUE TITLE
Traffic sign icons BE

### ISSUE THREAD

**Issue by Vakonof** [yopaseopor/traffic_signs_preset_JOSM#25]
There are a few Belgian presets that have a wrong traffic sign assigned to them.

- "No motor vehicles" should use sign C5-C7-C9 instead of C5-C7. That way mopeds, mofas and speed pedelecs (all motor vehicles) are also included.
- "No motorcycles" should use C7 instead of C6. The latter is used for quadbikes
- "No moped" should use C9 instead of C7. The latter is used for motorcycles.
- "Goods vehicles" and "End Goods vehicles" don't exist anymore and can be removed.

**Comment by yopaseopor** [comment]
Test it. Thank you for your information
