### ISSUE TITLE
ferry icon changed

### ISSUE THREAD

**Issue by Klumbumbus** [yopaseopor/traffic_signs_preset_JOSM#4]
the josm internal ferry icon changed.

old path: "presets/ferry.png"
new path: "styles/standard/nautical/ferry.svg"

**Comment by yopaseopor** [comment]
Icons are copied from JOSM but trying to avoid wrong path errors I have copied all the icons also in zip's preset so icon has the same path (one folder of the zip preset it is called "presets").

Thank you for your information :+1:

**Comment by Klumbumbus** [comment]
OK, however this has two disadvantages.
- You will stay with the old icons even when some gets updated in JOSM. (During the process of HIDPI support we plan to replace all png icons by svg icons, see https://josm.openstreetmap.de/ticket/9995) This will happen maybe in the next months.

- The download size of the preset is increased.

Also note that not all icons are in the "Presets" folder. A lot are in the osm svn: https://trac.openstreetmap.org/browser/subversion/applications/share/map-icons/classic.small
However we will move them all to the Presets folder in the next weeks. I just added you to the ticket, so you will get informed: https://josm.openstreetmap.de/ticket/13084
