### ISSUE TITLE
changed icon paths

### ISSUE THREAD

**Issue by Klumbumbus** [yopaseopor/traffic_signs_preset_JOSM#6]
JOSM has [moved](https://josm.openstreetmap.de/ticket/13084#comment:21) some icons and this preset needs an update.
All icon paths in presets starting with "styles/standard/..." start now with "presets/..."

**Comment by yopaseopor** [comment]
To avoid path problems with JOSM I have copied all the JOSM icons to the preset so all the icons are directed to the preset itself, nor JOSM. So I hope preset won't have any problem.

**Comment by Klumbumbus** [comment]
I just downloaded your zip file. There are 4 icons with paths starting with "styles/standard/...". They are no longer availible and they are not in your zip file. Your zip file contains only a small part of all preset icons (the icons from this folder: https://josm.openstreetmap.de/browser/josm/trunk/images/presets). However today we added 600 more icons to this folder (which were stored at a complete different place before.)

Also note that you copied the josm icons twice in the zip file. Directly in the zip file and also in a subfolder "presets".

**Comment by yopaseopor** [comment]
I fixed the path of the icons. I hope I did it correctly.

**Comment by Klumbumbus** [comment]
Seems fixed, however there are two new errors:

ERROR: Failed to locate image 'ES_traffic_sign_dir.png'
WARNING:  Direction: Could not get presets icon ES_traffic_sign_dir.png
ERROR: Failed to locate image 'CAT_radar.png'
WARNING:  Others: Could not get presets icon CAT_radar.png

**Comment by yopaseopor** [comment]
I fixed it all (I hope)

**Comment by Klumbumbus** [comment]
Yes, all errors fixed now. Thanks!
