### ISSUE TITLE
Reduce size of zip archive by removing unneeded files

### ISSUE THREAD

**Issue by don-vip** [yopaseopor/traffic_signs_preset_JOSM#7]
The zip archive is very huge (22 MB) and contains a lot of unneeded data:
- test
- .travis.yml
- Presets_Traffic_signs-preset - copia.xmlnomore
- Presets_Traffic_signs-preset.xml1x1
- Presets_Traffic_signs-preset.xmlsimple

Can you please remove them from zip archive?

**Comment by Klumbumbus** [comment]
seems fixed

**Comment by Klumbumbus** [comment]
no longer fixed.
test and travis.yml are back in the zip file
