### ISSUE TITLE
old icon path

### ISSUE THREAD

**Issue by Klumbumbus** [yopaseopor/traffic_signs_preset_JOSM#8]
In JOSM we reordered a lot icons and replaced some png by svg. (related [JOSM ticket](https://josm.openstreetmap.de/ticket/13217))
There is 14 times icon="presets/guidepost.png" in your preset file (the only icon left reffering to JOSM internal iconpaths). The new icon path is now "presets/misc/information/guidepost.svg". Or you use your interal copy "traffic_signs_presets/guidepost.png"

**Comment by yopaseopor** [comment]
Thanks , I forgot this path and it is replicated in every country I have. Now it is fixed , referring to the inside preset's icon.

**Comment by Klumbumbus** [comment]
There is a typo in line 499: icon="traffic_signs_traffic_signs_presets/guidepost.png"

**Comment by Klumbumbus** [comment]
Fixed. Thanks.
