### ISSUE TITLE
Typos "cicleway:*"

### ISSUE THREAD

**Issue by simon04** [yopaseopor/traffic_signs_preset_JOSM#9]
Reported via https://lists.openstreetmap.org/pipermail/josm-dev/2016-August/007740.html by @joto
> ... contains the keys "cicleway:segregated" and "cicleway:foot" which look like typos to me. Also "traffic_sign,traffic_sign:forward,traffic_sign:backward" as one key. That is probably meant to be three keys.

**Comment by yopaseopor** [comment]
I have fixed it. Thanks for the warning.
